### ISSUE TITLE
Post Deliverable 1

### ISSUE THREAD

**Issue by celenastefanie** [taylorsargent/simple-chat-app#12]
# Progress

Paper Wireframes
  - [ ] **404 page**
  - [x] Chat (main) page
  - [x] Members List
  - [x] Login Page
  - [ ] **Notifications**
    - [x] Joined
    - [ ] **Left**

Interactive Wireframes
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Login Page
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Login Page
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues

Completed: #4, #5, #6, #7, 

# Positives
+ All layouts were approved
+ Followed classic design trends associated with chat rooms
+ I think we're starting to understand how this works??

# Improvements
+ Do your homework! Please :)

# Request for Feedback
+ Nothing yet, just wondering how we will be contributing to one html with 4 people

@ericadamski

**Comment by ericadamski** [comment]
You guys are 💅ing it! Also you _won't_ be working in 1 html file :)
